# Install Library

In [23]:
%pip install numpy
%pip install pandas

Requirement already satisfied: numpy in ./.venv/lib/python3.10/site-packages (1.25.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in ./.venv/lib/python3.10/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in ./.venv/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in ./.venv/lib/python3.10/site-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

# Import Library

In [24]:
import numpy as np
import pandas as pd
import csv
from datetime import datetime

# Functions

In [25]:
def has_numbers(input: str):
    return any(char.isdigit() for char in input)

In [26]:
# -*- coding: utf-8 -*-
def is_english(s):
    try:
        s.encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        return False
    else:
        return True

In [27]:
def save_file(name_file,header, data):
    with open(name_file+'.csv', 'w') as file:
        # 2. Create a CSV writer
        writer = csv.writer(file)
        # 3. Write data to the file
        writer.writerow(header)
        writer.writerows(data)

# Read CSV

In [28]:
df = pd.read_csv("data_raw/books_raw.csv", encoding='utf-8')
df

,book_title,pushlisher,author,price,category,rating,images,desc,publication_date,page,product_dimensions,rating_count,reviews
0,Assistant to the Villain,"Entangled Publishing, LLC",Hannah Nicole Maehrer,$19.99&nbsp;,"['Comic Fantasy', 'Fantasy Romance', 'Science ...",4.8,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content content-spacing""><...",08/29/2023,352.0,5.80(w) x 8.70(h) x 1.00(d),8,"[['5', ' Such a fun read! ', '2', '0', '2023..."
1,My Roommate Is a Vampire,Penguin Publishing Group,Jenna Levine,$15.30&nbsp;,"['Humorous Contemporary Romance', 'Vampire Rom...",4.1,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content content-spacing""><...",08/29/2023,352.0,5.10(w) x 8.20(h) x 0.90(d),8,"[['5', ' A warm and fuzzy vampire book.. yes..."
2,23 1/2 Lies,Grand Central Publishing,James Patterson,$18.99&nbsp;,"['Crime Thrillers', 'Mystery &amp; Crime', 'Cr...",5.0,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/12/2023,448.0,5.40(w) x 8.20(h) x 1.30(d),2,"[['5', ' Great Reading! ', '0', '0', '2023-0..."
3,Godkiller: A Novel,HarperCollins Publishers,Hannah Kaner,$17.09&nbsp;,"['Adventure fantasy-&gt;Other', 'Epic Fantasy'...",4.5,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/12/2023,304.0,7.90(w) x 5.20(h) x 1.00(d),4,"[['4', ' Exciting debut ', '3', '0', '2023-0..."
4,"You, Again: A Novel",Random House Publishing Group,Kate Goldbeck,$16.20&nbsp;,"['Humorous Contemporary Romance', 'Romance - F...",4.8,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/12/2023,448.0,5.10(w) x 7.90(h) x 1.10(d),8,"[['5', ' amazing banter ', '0', '1', '2023-0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,I am Jackie Robinson,Penguin Young Readers Group,Brad Meltzer,$9.99&nbsp;,"['African American Athletes - Kids Biography',...",5.0,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",08/01/2023,40.0,7.30(w) x 7.30(h) x 0.25(d),1,"[['5', ' Excellent! ', '0', '1', '2015-02-06']]"
1988,Dark Corners of the Old Dominion,Death Knell Press,Joseph Maddrey (Editor),$14.99&nbsp;,[],(0),['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/08/2023,232.0,6.00(w) x 9.00(h) x 0.53(d),0,[]
1989,Seven Summers (And a Few Bummers),Robert Stephen Welch,Bob Welch,$24.95&nbsp;,[],5.0,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/11/2023,378.0,6.00(w) x 9.00(h) x 0.84(d),1,"[['5', ' Two for One ', '0', '0', '2023-09-1..."
1990,Reframe Your Brain: The User Interface for Hap...,"Scott Adams, Inc.",Scott Adams,$19.99&nbsp;,[],(0),['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",08/16/2023,246.0,5.50(w) x 8.50(h) x 0.56(d),0,[]
1991,The Knight Blooms Behind Castle Walls Vol. 3,Seven Seas Entertainment,Masanari Yuduka,$13.99&nbsp;,[],(0),['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",08/01/2023,176.0,4.99(w) x 7.13(h) x 0.50(d),0,[]

# Modified Data

## Repare Data Modified

In [29]:
data_modified = df.copy()
data_modified.reindex
data_modified

,book_title,pushlisher,author,price,category,rating,images,desc,publication_date,page,product_dimensions,rating_count,reviews
0,Assistant to the Villain,"Entangled Publishing, LLC",Hannah Nicole Maehrer,$19.99&nbsp;,"['Comic Fantasy', 'Fantasy Romance', 'Science ...",4.8,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content content-spacing""><...",08/29/2023,352.0,5.80(w) x 8.70(h) x 1.00(d),8,"[['5', ' Such a fun read! ', '2', '0', '2023..."
1,My Roommate Is a Vampire,Penguin Publishing Group,Jenna Levine,$15.30&nbsp;,"['Humorous Contemporary Romance', 'Vampire Rom...",4.1,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content content-spacing""><...",08/29/2023,352.0,5.10(w) x 8.20(h) x 0.90(d),8,"[['5', ' A warm and fuzzy vampire book.. yes..."
2,23 1/2 Lies,Grand Central Publishing,James Patterson,$18.99&nbsp;,"['Crime Thrillers', 'Mystery &amp; Crime', 'Cr...",5.0,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/12/2023,448.0,5.40(w) x 8.20(h) x 1.30(d),2,"[['5', ' Great Reading! ', '0', '0', '2023-0..."
3,Godkiller: A Novel,HarperCollins Publishers,Hannah Kaner,$17.09&nbsp;,"['Adventure fantasy-&gt;Other', 'Epic Fantasy'...",4.5,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/12/2023,304.0,7.90(w) x 5.20(h) x 1.00(d),4,"[['4', ' Exciting debut ', '3', '0', '2023-0..."
4,"You, Again: A Novel",Random House Publishing Group,Kate Goldbeck,$16.20&nbsp;,"['Humorous Contemporary Romance', 'Romance - F...",4.8,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/12/2023,448.0,5.10(w) x 7.90(h) x 1.10(d),8,"[['5', ' amazing banter ', '0', '1', '2023-0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,I am Jackie Robinson,Penguin Young Readers Group,Brad Meltzer,$9.99&nbsp;,"['African American Athletes - Kids Biography',...",5.0,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",08/01/2023,40.0,7.30(w) x 7.30(h) x 0.25(d),1,"[['5', ' Excellent! ', '0', '1', '2015-02-06']]"
1988,Dark Corners of the Old Dominion,Death Knell Press,Joseph Maddrey (Editor),$14.99&nbsp;,[],(0),['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/08/2023,232.0,6.00(w) x 9.00(h) x 0.53(d),0,[]
1989,Seven Summers (And a Few Bummers),Robert Stephen Welch,Bob Welch,$24.95&nbsp;,[],5.0,['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",09/11/2023,378.0,6.00(w) x 9.00(h) x 0.84(d),1,"[['5', ' Two for One ', '0', '0', '2023-09-1..."
1990,Reframe Your Brain: The User Interface for Hap...,"Scott Adams, Inc.",Scott Adams,$19.99&nbsp;,[],(0),['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",08/16/2023,246.0,5.50(w) x 8.50(h) x 0.56(d),0,[]
1991,The Knight Blooms Behind Castle Walls Vol. 3,Seven Seas Entertainment,Masanari Yuduka,$13.99&nbsp;,[],(0),['https://prodimage.images-bn.com/lf?set=key%5...,"<br/><div class=""bs-content ""><br/><div class=...",08/01/2023,176.0,4.99(w) x 7.13(h) x 0.50(d),0,[]

### Categorise

In [30]:
list_cate = []
mapping_table = str.maketrans({"'": '', 
                               '[': '', 
                               ']': ''})

for i in range(len(data_modified['category'])):
    cate = data_modified['category'][i].translate(mapping_table).replace('&amp;', '&').split(",")
    cate = [cat.strip() for cat in cate if not has_numbers(cat) and cat != " Awards"]
    if len(cate) == 1:
        cate[0] = "Orther Books"
    list_cate.append(cate)
data_modified['category'].update(pd.Series(list_cate))
data_modified['category']

0       [Comic Fantasy, Fantasy Romance, Science Ficti...
1       [Humorous Contemporary Romance, Vampire Romanc...
2       [Crime Thrillers, Mystery & Crime, Crime Ficti...
3       [Adventure fantasy-&gt;Other, Epic Fantasy, Sc...
4       [Humorous Contemporary Romance, Romance - Frie...
                              ...
1987    [African American Athletes - Kids Biography, A...
1988                                       [Orther Books]
1989                                       [Orther Books]
1990                                       [Orther Books]
1991                                       [Orther Books]
Name: category, Length: 1992, dtype: object

### Price

In [31]:
data_modified["price"] = [p.replace("&nbsp;","") for p in data_modified["price"]]
data_modified['price']

0       $19.99
1       $15.30
2       $18.99
3       $17.09
4       $16.20
         ...
1987     $9.99
1988    $14.99
1989    $24.95
1990    $19.99
1991    $13.99
Name: price, Length: 1992, dtype: object

### Images

In [32]:
list_images = []
mapping_table = str.maketrans({"'": '', 
                               '[': '', 
                               ']': ''})
for i in range(len(data_modified['images'])):
    images = data_modified['images'][i].split("', '")
    images = [image.translate(mapping_table).strip() for image in images]
    list_images.append(images)
data_modified['images'].update(pd.Series(list_images))
data_modified["images"]

0       [https://prodimage.images-bn.com/lf?set=key%5B...
1       [https://prodimage.images-bn.com/lf?set=key%5B...
2       [https://prodimage.images-bn.com/lf?set=key%5B...
3       [https://prodimage.images-bn.com/lf?set=key%5B...
4       [https://prodimage.images-bn.com/lf?set=key%5B...
                              ...
1987    [https://prodimage.images-bn.com/lf?set=key%5B...
1988    [https://prodimage.images-bn.com/lf?set=key%5B...
1989    [https://prodimage.images-bn.com/lf?set=key%5B...
1990    [https://prodimage.images-bn.com/lf?set=key%5B...
1991    [https://prodimage.images-bn.com/lf?set=key%5B...
Name: images, Length: 1992, dtype: object

### Ratings

In [33]:
mapping_table = str.maketrans({'(': '', 
                               ')': ''})
data_modified["rating"] = [r.translate(mapping_table) for r in data_modified["rating"]]
data_modified['rating']

0       4.8
1       4.1
2       5.0
3       4.5
4       4.8
       ...
1987    5.0
1988      0
1989    5.0
1990      0
1991      0
Name: rating, Length: 1992, dtype: object

### Reviews

In [34]:
mapping_table = str.maketrans({"'": '',
                               '"': '', 
                               '[': '', 
                               ']': ''})
list_reviews = []
for i in range(len(data_modified['reviews'])):
    reviews = data_modified['reviews'][i].split("], [")
    lst_revs = []
    for j in range(len(reviews)):
        rev = reviews[j].translate(mapping_table).split(",")
        rev = [r.strip() for r in rev if type(r) != int]
        if len(rev) == 1:
            rev[0] = None
        rev.insert(0,i)
        lst_revs.append(rev)
    list_reviews.append(lst_revs)
data_modified["reviews"] = list_reviews
data_modified["reviews"]

0       [[0, 5, Such a fun read!, 2, 0, 2023-09-02], [...
1       [[1, 5, A warm and fuzzy vampire book.. yes!, ...
2       [[2, 5, Great Reading!, 0, 0, 2023-09-19], [2,...
3       [[3, 4, Exciting debut, 3, 0, 2023-09-07], [3,...
4       [[4, 5, amazing banter, 0, 1, 2023-07-27], [4,...
                              ...
1987            [[1987, 5, Excellent!, 0, 1, 2015-02-06]]
1988                                       [[1988, None]]
1989           [[1989, 5, Two for One, 0, 0, 2023-09-13]]
1990                                       [[1990, None]]
1991                                       [[1991, None]]
Name: reviews, Length: 1992, dtype: object

### Save

In [35]:
data_modified.to_csv("data_raw/books_modified.csv", sep=',', index=True, encoding='utf-8', index_label="id")

## Repare Data Books DB

In [36]:
books_db = data_modified.copy()

In [37]:
books_db["images"] = [str(i).replace("[","{").replace("]","}") for i in books_db["images"]]

In [38]:
books_db.to_csv("data_raw/books_db.csv", sep=',', index=True, encoding='utf-8', index_label="id")

## Repare Data Genres DB

In [65]:
genres_db = data_modified['category'].copy()
# genres_db.unique()
genres_table = pd.DataFrame(columns=['name'])
list_genres = [g for genres in genres_db for g in genres]
genres = pd.Series(list_genres).drop_duplicates().reset_index().drop(columns='index')
genres_table['name'] = genres
genres_table

                                       name
0                             Comic Fantasy
1                           Fantasy Romance
2                 Science Fiction & Fantasy
3                           Fantasy Fiction
4                                   Romance
...                                     ...
1351                Baseball Players - Kids
1352     African Americans - Kids Biography
1353  Sports & Adventurers - Kids Biography
1354              Sports & Adventure - Kids
1355                        Baseball - Kids

[1356 rows x 1 columns]

## Repare Data Reviews DB

In [ ]:
reviews_db = data_modified['reviews'].copy()
reviews_db

0       [[0, 5, Such a fun read!, 2, 0, 2023-09-02], [...
1       [[1, 5, A warm and fuzzy vampire book.. yes!, ...
2       [[2, 5, Great Reading!, 0, 0, 2023-09-19], [2,...
3       [[3, 4, Exciting debut, 3, 0, 2023-09-07], [3,...
4       [[4, 5, amazing banter, 0, 1, 2023-07-27], [4,...
                              ...
1987            [[1987, 5, Excellent!, 0, 1, 2015-02-06]]
1988                                       [[1988, None]]
1989           [[1989, 5, Two for One, 0, 0, 2023-09-13]]
1990                                       [[1990, None]]
1991                                       [[1991, None]]
Name: reviews, Length: 1992, dtype: object

In [ ]:
list_rev = []
reviews_table = pd.DataFrame(columns=['books_id',
            'liked',
            'disliked',
            'reported',
            'comments',
            'rating',
            'created_at'])
for rev in reviews_db:
    for r in rev:
        if len(rev) != 1:
            temp = {
                'books_id': r[0],
                'liked': r[3],
                'disliked': r[4],
                'reported': False,
                'comments':r[2],
                'is_deleted':False,
                'rating':r[1],
                'created_at': datetime.strptime(r[-1].replace("-","/"), '%Y/%m/%d')
                }
            if has_numbers(r[3]):
                reviews_table.loc[len(reviews_table)] = temp
reviews_table

,books_id,liked,disliked,reported,comments,rating,created_at
0,0,2,0,False,Such a fun read!,5,2023-09-02
1,0,1,0,False,My new favorite book,5,2023-08-27
2,0,4,0,False,Great romcon.. a must read,5,2023-09-01
3,0,1,0,False,Rated 4.5 Stars,5,2023-08-29
4,0,1,0,False,I’m Obsessed,5,2023-09-04
...,...,...,...,...,...,...,...
4104,1974,0,0,False,Back in Shadow Lake,5,2023-06-18
4105,1974,0,0,False,Great addition to story,5,2023-08-21
4106,1980,0,0,False,The only book moms need to read!,5,2023-09-06
4107,1980,0,0,False,Let Go Of Guilt,5,2023-08-12
4108,1980,0,0,False,A Field Guide to Emotionally Healthy Motherhood,5,2023-08-11

In [ ]:
reviews_table.to_csv("data_raw/reviews_db.csv", sep=',', index=True, encoding='utf-8', index_label="id")